baseURL = 'https://readingnl.nl/'
languageCode = 'ru'
title = 'Книжный клуб в Нидерландах'
theme = 'PaperMod'

[params]
    defaultTheme = 'dark'
    disableThemeToggle = 'true'
    [params.profileMode]
        Title = 'Книжный клуб в Нидерландах'
        enabled='true'
        imageUrl='/images/rodina.jpg'
        [[params.profileMode.buttons]]
            name = 'О клубе'
            url = '/about'
        [[params.profileMode.buttons]]
            name = 'Правила'
            url = '/rules'
        [[params.profileMode.buttons]]
            name = 'Контакты'
            url = '/contact'

[[module.mounts]]
    source = 'static'
    target = 'static'
[[module.mounts]]
    source = 'images'
    target = 'static/images'